services:
  coffee-cupping-postgres:
    image: postgres:15-alpine
    container_name: coffee-cupping-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: UTC
      PGTZ: UTC
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - coffee-cupping-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  coffee-cupping-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coffee-cupping-api
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    ports:
      - "${HTTP_PORT}:8080"
    environment:
      TZ: UTC
      POSTGRES_HOST: coffee-cupping-postgres
      POSTGRES_PORT: 5432
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_URL: postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@coffee-cupping-postgres:5432/${POSTGRES_DBNAME}?sslmode=disable
      HTTP_PORT: ${HTTP_PORT}
      JWT_ACCESS_TOKEN_KEY: ${JWT_ACCESS_TOKEN_KEY}
      JWT_ACCESS_TOKEN_EXPIRES_IN: ${JWT_ACCESS_TOKEN_EXPIRES_IN}
      JWT_REFRESH_TOKEN_KEY: ${JWT_REFRESH_TOKEN_KEY}
      JWT_REFRESH_TOKEN_EXPIRES_IN: ${JWT_REFRESH_TOKEN_EXPIRES_IN}
      JWT_REGISTER_TOKEN_KEY: ${JWT_REGISTER_TOKEN_KEY}
      JWT_REGISTER_TOKEN_EXPIRES_IN: ${JWT_REGISTER_TOKEN_EXPIRES_IN}
      JWT_LOGIN_TOKEN_KEY: ${JWT_LOGIN_TOKEN_KEY}
      JWT_LOGIN_TOKEN_EXPIRES_IN: ${JWT_LOGIN_TOKEN_EXPIRES_IN}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_APP_PASSWORD: ${SMTP_APP_PASSWORD}
    networks:
      - coffee-cupping-network
    depends_on:
      - coffee-cupping-postgres

volumes:
  postgres-data:
    name: postgres-data
    driver: local

networks:
  coffee-cupping-network:
    name: coffee-cupping-network
    driver: bridge
    ipam:
      driver: default
