# Development Environment Override
# This file extends the base docker-compose.yml for development
services:
  coffee-cupping-postgres:
    container_name: coffee-cupping-postgres-dev
    environment:
      POSTGRES_DB: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data

  coffee-cupping-api:
    container_name: coffee-cupping-api-dev
    environment:
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_URL: ${POSTGRES_DB_URL}
      HTTP_PORT: ${HTTP_PORT}
      JWT_ACCESS_TOKEN_KEY: ${JWT_ACCESS_TOKEN_KEY}
      JWT_ACCESS_TOKEN_EXPIRES_IN: ${JWT_ACCESS_TOKEN_EXPIRES_IN}
      JWT_REFRESH_TOKEN_KEY: ${JWT_REFRESH_TOKEN_KEY}
      JWT_REFRESH_TOKEN_EXPIRES_IN: ${JWT_REFRESH_TOKEN_EXPIRES_IN}
      JWT_REGISTER_TOKEN_KEY: ${JWT_REGISTER_TOKEN_KEY}
      JWT_REGISTER_TOKEN_EXPIRES_IN: ${JWT_REGISTER_TOKEN_EXPIRES_IN}
      JWT_LOGIN_TOKEN_KEY: ${JWT_LOGIN_TOKEN_KEY}
      JWT_LOGIN_TOKEN_EXPIRES_IN: ${JWT_LOGIN_TOKEN_EXPIRES_IN}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_APP_PASSWORD: ${SMTP_APP_PASSWORD}
      LOGGER_LOG_LEVEL: ${LOGGER_LOG_LEVEL}
    ports:
      - "${HTTP_PORT}:8080"
    volumes:
      - ./logs:/app/logs

volumes:
  postgres-dev-data:
    name: postgres-dev-data
    driver: local
