// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"backend/config"
	"backend/internal/infrastructure/repository/postgres"
	"backend/internal/usecase/user"
	"backend/internal/usecase/user/implement"
	"gorm.io/gorm"
)

// Injectors from user.wire.go:

func NewUserAuthService(cfg *config.Config, db *gorm.DB) user.UserAuthService {
	userRepository := postgres.NewUserRepo(db)
	refreshTokenRepository := postgres.NewRefreshTokenRepo(db)
	userAuthService := implement.NewUserAuthService(cfg, userRepository, refreshTokenRepository)
	return userAuthService
}
