// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"backend/internal/infrastructure/repository/postgres"
	"backend/internal/infrastructure/uow"
	"backend/internal/usecase/user"
	"backend/internal/usecase/user/implement"
	"gorm.io/gorm"
)

// Injectors from user_wire.go:

func NewUserAuthService(db *gorm.DB) user.UserAuthService {
	userAuthUow := uow.NewUserAuthUow(db)
	userRepository := postgres.NewUserRepo(db)
	refreshTokenRepository := postgres.NewRefreshTokenRepo(db)
	userAuthService := implement.NewUserAuthService(userAuthUow, userRepository, refreshTokenRepository)
	return userAuthService
}
