// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package role

import (
	"backend/internal/infrastructure/repository/postgres"
	"backend/internal/usecase/role"
	"backend/internal/usecase/role/implement"
	"gorm.io/gorm"
)

// Injectors from role_wire.go:

func NewRoleService(db *gorm.DB) role.RoleService {
	roleRepository := postgres.NewRoleRepo(db)
	roleService := implement.NewRoleService(roleRepository)
	return roleService
}
