name: Build Image
on:
    workflow_call:
      inputs:
        actor:
          required: true
          type: string
        repository:
          required: true
          type: string
jobs:
    build-service-image:
        name: Build Service Image
        runs-on: [ubuntu-latest]
        env:
          REGISTRY: ghcr.io/${{ inputs.actor }}/${{ inputs.repository }}
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4
          - name: Setup Docker Buildx
            uses: docker/setup-buildx-action@v2
          - name: Login to GitHub Container Registry
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{ inputs.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
          - name: Set TAG environment variable base on commit brand
            run: |
              if [ "${GITHUB_REF_NAME}" = "dev" ]; then
                echo "TAG=dev-latest" >> $GITHUB_ENV
                echo "PROFILE=api-dev" >> $GITHUB_ENV
              else
                echo "TAG=prod-latest" >> $GITHUB_ENV
                echo "PROFILE=api-prod" >> $GITHUB_ENV
              fi
          - name: Build and Push Image
            run: |
              docker compose -f compose.yaml --profile ${{env.PROFILE}} build --parallel
              docker compose -f compose.yaml --profile ${{env.PROFILE}} push
        